# Generated by Django 6.0.5 on 2026-05-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("OWNER_FRONT", "제공자 등록 - 앞면"),
                    ("OWNER_BACK", "제공자 등록 - 뒷면"),
                    ("OWNER_LEFT", "제공자 등록 - 좌측"),
                    ("OWNER_RIGHT", "제공자 등록 - 우측"),
                    ("RENTER_FRONT", "대여자 반납 - 앞면"),
                    ("RENTER_BACK", "대여자 반납 - 뒷면"),
                    ("RENTER_LEFT", "대여자 반납 - 좌측"),
                    ("RENTER_RIGHT", "대여자 반납 - 우측"),
                ],
                default="OWNER_FRONT",
                max_length=20,
            ),
        ),
    ]
